apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: default
spec:
  type: LoadBalancer  # ClusterIP → LoadBalancer に変更
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
